{% set name = "sage" %}
{% set version = "8.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py!=27]

requirements:
  build:
    - python
  run:
    - alabaster
    - appnope  # [osx]
    - arb
    - backports.shutil_get_terminal_size
    - backports_abc
    - bdw-gc
    - boost-cpp
    - brial
    - cddlib
    - certifi
    - cliquer
    - configparser
    - cvxopt
    - cycler
    - cysignals
    - decorator
    - docutils
    - ecl
    - eclib
    - ecm
    - entrypoints
    - fflas-ffpack
    - flintqs
    - fplll
    - fpylll
    - freetype
    - functools32
    - future
    - gap
    - gf2x
    - gfan
    - giac
    - givaro
    - glpk
    - gmp
    - gsl
    - iml
    - ipykernel
    - ipython
    - ipython_genutils
    - ipywidgets
    - jinja2
    - jsonschema
    - jupyter_client
    - jupyter_core
    - lcalc
    - libflint
    - libgap
    - libgd
    - libiconv
    - libpng
    - linbox
    - lrcalc
    - m4ri
    - m4rie
    - matplotlib
    - maxima
    - mistune
    - mpc
    - mpfi
    - mpfr
    - mpmath
    - nauty
    - nbconvert
    - nbformat
    - ncurses
    - networkx
    - notebook
    - ntl
    - numpy
    - openblas
    - palp
    - pari
    - path.py
    - pathlib2
    - pexpect
    - pickleshare
    - planarity
    - ppl
    - prompt_toolkit
    - psutil
    - ptyprocess
    - pycrypto
    - pygments
    - pynac
    - pyparsing
    - python
    - python-dateutil
    - pytz
    - pyzmq
    - ratpoints
    - readline
    - rpy2
    - rubiks
    - rw
    - sagelib {{ version }}
    - sagemath-db-combinatorial-designs
    - sagemath-db-conway-polynomials 0.5.*
    - sagemath-db-elliptic-curves
    - sagemath-db-graphs
    - sagemath-db-polytopes
    - scipy
    - simplegeneric
    - singledispatch
    - singular
    - six
    - sqlite
    - ssl_match_hostname
    - symmetrica
    - sympow
    - sympy
    - terminado
    - tornado
    - traitlets
    - wcwidth
    - widgetsnbextension
    - zeromq
    - zlib
    - zn_poly

    #- sagetex
    #- pillow

    # sagenb dependencies with conda-packages
    #- babel
    #- itsdangerous
    #- flask
    #- flask-babel
    #- flask-openid
    #- markupsafe
    #- python-openid
    #- twisted
    #- speaklater
    #- werkzeug
    #- zope.interface

    # sagenb dependencies
    #- jmol
    #- mathjax
    #- tachyon
    #- thebe
    #- sagenb
    #- sagenb_export
    #- flask_autoindex
    #- flask_oldsessions
    #- flask_silk

    # docs
    #- sphinx
    #- snowballstemmer
    #- imagesize

    # dev
    #- bzip2
    #- gcc
    #- git

    # build-time dependencies
    #- vcversioner
    #- setuptools_scm

test:
  commands:
    - sage -v
    - sage -c 1+1


about:
  home: http://sagemath.org
  license: GPLv2+
  summary: 'Sage - Open Source Mathematical Software'
  description: |
    Creating a Viable Open Source Alternative to Magma, Maple, Mathematica, and MATLAB.
  doc_url: https://doc.sagemath.org/
  dev_url: https://trac.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
