{% set name = "sage" %}
{% set version = "10.5" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 2
  noarch: generic

requirements:
  run:
    # We require all dependencies with at least that version that upstream uses
    # in their SPKGs. For packages that (seem to) use semantic versioning and
    # are at least 1.0.0, we limit the version to the next major release.
    - blas-devel
    - conway-polynomials >=0.10
    - cvxopt >=1.3.2,<2
    - cypari2
    - flintqs >=1.0,<2
    - fplll >=5.4.5,<6
    - fpylll >=0.6.0
    - gap-defaults >=4.12.2
    - gfan >=0.6.2
    - ipykernel >=6.6.0,<7
    - ipython >=8.18.1,<9  # TODO: Remove this line with the next sagelib upgrade; it's in the sagelib recipe now
    - ipywidgets >=8.1.1,<9
    - jmol >=14.29.52,<15
    - jupyter_client >=8.3.1,<9
    - matplotlib-base >=3.8.0,<4
    - maxima >=5.46.0,<6
    - mpmath >=1.3.0,<2
    - nbclient >=0.8.0,<0.9
    - nbconvert >=7.9.2,<8
    - nbformat >=5.9.2,<6
    - networkx >=3.2.1,<4
    - notebook >=7.1.1,<8
    - palp >=2.11,<3
    - pari >=2.15.4  # this pin is slightly more strict than the one from the pinning-feedstock
    - pillow >=10.1.0,<11
    - pkg-config
    - pkgconfig
    - primecountpy >=0.1.0,<0.2.0  # TODO: Remove this line with the next sagelib upgrade; it's in the sagelib recipe now
    - python >=3.9
    - pythran >=0.14.0,<0.15
    - pytz >=2023.3.post1
    - rpy2 >=3.4.5,<4
    - rubiks >=20070912
    - sagelib {{ version }}
    - sagemath-db-combinatorial-designs >=20140630
    - sagemath-db-elliptic-curves >=0.8.1
    - sagemath-db-graphs >=20210214
    - sagemath-db-polytopes >=20170220
    - sagetex >=3.6.1,<4
    - scipy >=1.12.0,<2
    - sphinx >=7.2.6,<8
    - sqlite >=3.36,<4
    - sympow >=2.023.6,<3
    - sympy >=1.12.1,<2
    - tachyon 0.99.*
    - widgetsnbextension >=4.0.9,<5
    - zn_poly

    #- sagenb_export
    # required for sage.misc.package.pip_installed_packages
    - pip

    # dev
    #- gcc
    #- git

    # build-time dependencies
    #- vcversioner
    #- setuptools_scm
    #- boost-cpp
    #- pkgconfig

test:
  requires:
    - bc
    - git
    - patch
  commands:
    - sage -v
    - sage -c 1+1
    - echo exit | sage

about:
  home: http://sagemath.org
  license: GPL-2.0-or-later
  license_file: COPYING.txt
  summary: 'Sage - Open Source Mathematical Software'
  description: |
    Creating a Viable Open Source Alternative to Magma, Maple, Mathematica, and MATLAB.
  doc_url: https://doc.sagemath.org/
  dev_url: https://github.com/sagemath/sage

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
    - alexjbest
