{% set name = "sage" %}
{% set version = "9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py3k and (py<36 or py>37)]

requirements:
  host:
    - python
  run:
    # We require all dependencies with at least that version that upstream uses
    # in their SPKGs. For packages that (seem to) use semantic versioning and
    # are at least 1.0.0, we limit the version to the next major release.
    - alabaster >=0.7.12
    - appnope >=0.1.0                                   # [osx]
    - arb
    - babel >=2.6.0,<3
    - backports.functools_lru_cache >=1.5,<2            # [py27]
    - backports.shutil_get_terminal_size >=1.0.0,<2     # [py27]
    - backports_abc >=0.5                               # [py27]
    - bdw-gc >=7.6.4,<9
    - bleach >=3.0.2,<4
    - brial
    - cddlib >=1!0.94j
    - certifi >=2019.3.9
    - cliquer
    - configparser >=3.7.3,<4                           # [py27]
    - cvxopt >=1.1.8,<2
    - cycler >=0.10.0
    - cypari2
    - cysignals
    - cython >=0.29.12
    - decorator >=4.4.0,<5
    - docutils >=0.14
    # ecl 16.1.3 causes unhandled SIGFPEs, see https://github.com/conda-forge/sagelib-feedstock/issues/44
    - ecl >=16.1.2,<16.1.3
    - eclib
    - ecm
    - entrypoints >=0.3
    - fflas-ffpack >=2.4.3
    - flintqs >=1.0,<2
    - fplll >=5.2.1,<6
    - fpylll >=0.4.1dev
    - freetype >=2.9.1,<3
    - functools32 >=3.2.3,<4                            # [py27]
    - future >=0.17.1
    - gap-defaults >=4.10.2
    - gf2x >=1.2,<2
    - gfan >=0.6.2
    - giac >=1.5.0.63,<2
    - givaro >=4.1.1,<5
    - glpk
    - gmp
    - gmpy2
    - gsl
    - iml
    - ipykernel >=4.8.2,<5
    - ipython >=5.8.0,<6
    - ipython_genutils >=0.2.0
    - ipywidgets >=7.4.2,<8
    - jinja2
    - jmol >=14.6.1,<15
    - jsonschema >=2.6.0,<3
    - jupyter_client >=5.2.4,<6
    - jupyter_core
    - lcalc
    - libbraiding
    - libflint
    - libgd
    - libhomfly
    - libiconv >=1.15,<2
    - libpng
    - linbox >=1.6.3
    - lrcalc
    - m4ri
    - m4rie
    - matplotlib-base >=2.2.4,<3
    - maxima >=5.42.2,<6
    - mistune >=0.8.4
    - mpc
    - mpfi
    - mpfr
    - mpmath >=1.1.0,<2
    - nauty >=2.6r7,<3
    - nbconvert >=5.4.0,<6
    - nbformat >=4.4.0,<5
    - ncurses >=6.0,<7
    - networkx >=2.2,<3
    - notebook >=5.7.6,<6
    - ntl
    - numpy
    - palp >=2.1,<3
    - pari >=2.11.2
    # path.py 7 has not been built for Python3 on conda-forge, so we use the latest version
    - path.py >=7
    - pathlib2 >=2.3.3,<3
    - pexpect >=4.6.0,<5
    - pkg-config
    - pkgconfig
    - pickleshare >=0.7.5
    - pillow >=5.3.0,<6
    - planarity
    - ppl
    - pplpy 
    - prompt_toolkit >=1.0.15,<2
    - psutil >=5.2.0,<6
    - ptyprocess >=0.5.1
    - pygments >=2.3.1,<3
    - pynac >=0.7.26,<0.8
    - pyparsing >=2.3.0,<3
    - python
    - python-dateutil >=2.5.3,<3
    - pytz >=2018.7
    - pyzmq >=18.1.0,<19
    - ratpoints
    - readline
    - rpy2 >=2.8.6,<4
    - rubiks >=20070912
    - rw
    - sagelib {{ version }}
    - sagemath-db-combinatorial-designs >=20140630
    - sagemath-db-conway-polynomials >=0.5
    - sagemath-db-elliptic-curves >=0.8
    - sagemath-db-graphs >=20161026
    - sagemath-db-polytopes >=20170220
    - sagenb >=1.1.2,<1.2
    - sagetex >=3.3
    - scipy >=1.2.0
    - simplegeneric >=0.8.1
    - singledispatch >=3.4.0.3,<4
    - singular
    - six >=1.12.0,<2
    - sphinx >=1.8.5,<2
    - sqlite >=3.22,<4
    - ssl_match_hostname >=3.5.0.1,<4                   # [py27]
    - symmetrica
    - sympow >=2.023.3,<3
    {% if version == "9.1" %}
    - sympy <1.6
    {% endif %}
    - sympy >=1.4,<2
    - tachyon 0.99.*
    - terminado >=0.8.1
    - three.js 110
    - tornado >=4.5.2,<7
    - traitlets >=4.3.2,<5
    - twisted >=18.4.0,<19
    - wcwidth >=0.1.7
    - widgetsnbextension >=3.4.2,<4
    - zeromq >=4.2.5,<5
    - zlib
    - zn_poly

    #- sagenb_export
    # required for sage.misc.package.pip_installed_packages
    - pip

    # dev
    #- gcc
    #- git

    # build-time dependencies
    #- vcversioner
    #- setuptools_scm
    #- boost-cpp
    #- pkgconfig

test:
  requires:
    - bc
    - git
  commands:
    - sage -v
    - sage -c 1+1
    - echo exit | sage

about:
  home: http://sagemath.org
  license: GPL-2.0-or-later
  summary: 'Sage - Open Source Mathematical Software'
  description: |
    Creating a Viable Open Source Alternative to Magma, Maple, Mathematica, and MATLAB.
  doc_url: https://doc.sagemath.org/
  dev_url: https://trac.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
