{% set name = "sage" %}
{% set version = "8.2" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 3
  skip: true  # [win]
  skip: true  # [py!=27]

requirements:
  host:
    - python
  run:
    # We require all dependencies with at least that version that upstream uses
    # in their SPKGs. For packages that (seem to) use semantic versioning and
    # are at least 1.0.0, we limit the version to the next major release.
    - alabaster >=0.7.10
    - appnope >=0.1.0                                   # [osx]
    - arb >=2.12.0,<3
    - babel >=2.3.4,<3
    - backports.functools_lru_cache >=1.4,<2            # [py27]
    - backports.shutil_get_terminal_size >=1.0.0,<2     # [py27]
    - backports_abc >=0.5                               # [py27]
    - bdw-gc >=7.2f,<8
    - bleach >=2.1.3,<3
    - boost-cpp >=1.61.0,<2
    - brial >=1.0.1,<2
    - cddlib 0.94g
    - certifi >=2017.11.5
    - cliquer >=1.21,<2
    - configparser >=3.5.0,<4                           # [py27]
    - cvxopt >=1.1.8,<2
    - cycler >=0.10.0
    - cypari2 >=1.1.4,<2
    - cysignals >=1.7.0,<2
    - cython >=0.28.1
    - decorator >=4.0.6,<5
    - docutils >=0.14
    - ecl >=16.1.2,<17
    - eclib >=20171002
    - ecm >=7.0.4,<8
    - entrypoints >=0.2.3
    - fflas-ffpack >=2.3.2,<2.4.0
    - flintqs >=1.0,<2
    - fplll >=5.2.0,<6
    - fpylll >=0.3.0dev
    - freetype >=2.8,<3
    - functools32 >=3.2.3,<4                            # [py27]
    - future >=0.16.0
    - gap >=4.8.6,<5
    - gf2x >=1.2,<2
    - gfan >=0.5
    - giac >=1.4.9.45,<2
    - givaro >=4.0.4,<5
    - glpk >=4.63,<5
    - gmp >=6.1.2,<7
    # SageMath uses GSL 2.3, however conda-forge is currently pinned to 2.2
    - gsl >=2.2,<3
    - iml >=1.0.4,<2
    - ipykernel >=4.7.0,<5
    - ipython >=5.5.0,<6
    - ipython_genutils >=0.2.0
    - ipywidgets >=7.1.1,<8
    - jinja2 >=2.10,<3
    - jmol >=14.6.1,<15
    - jsonschema >=2.6.0,<3
    - jupyter_client >=5.2.2,<6
    - jupyter_core >=4.4.0,<5
    - lcalc >=1.23,<2
    - libflint >=2.5.2,<3
    - libgap >=4.8.6,<5
    - libgd >=2.1.1.1,<3
    - libiconv >=1.14,<2
    - libpng >=1.6.29,<2
    - linbox >=1.5.2,<1.6
    - lrcalc >=1.2,<2
    - m4ri >=20140914
    - m4rie >=20150908
    - matplotlib >=2.1.0,<3
    - maxima >=5.39.0,<6
    - mistune >=0.7.3
    - mpc >=1.1.0,<2
    - mpfi >=1.5.1,<2
    - mpfr >=4.0.1,<5
    - mpmath >=1.0.0,<2
    - nauty >=2.6r7,<3
    - nbconvert >=5.3.1,<6
    - nbformat >=4.4.0,<5
    # Sage uses 6.0 but our GAP uses 5.9, see https://github.com/conda-forge/gap-feedstock/pull/11
    - ncurses >=5.9,<7
    - networkx >=1.11,<2
    - notebook >=5.3.1,<6
    - ntl >=10.3.0,<11
    - numpy >=1.13.3,<2
    - openblas >=0.2.20
    - palp >=2.1,<3
    # Sage uses an unreleased 2.10 pre-release
    - pari >=2.9,<3
    - path.py >=11,<12
    - pathlib2 >=2.3.0,<3
    - pexpect >=4.1.0,<5
    - pickleshare >=0.7.4
    - pillow >=4.3.0,<5
    - planarity >=3.0.0.5,<4
    - ppl >=1.2,<2
    - prompt_toolkit >=1.0.15,<2
    - psutil >=5.2.0,<6
    - ptyprocess >=0.5.1
    - pycrypto >=2.6.1,<3
    - pygments >=2.2.0,<3
    - pynac >=0.7.16
    - pyparsing >=2.2.0,<3
    - python   # [py==27]
    - python-dateutil >=2.5.3,<3
    - pytz >=2017.3
    - pyzmq >=17.0.0,<18
    - ratpoints >=2.1.3,<3
    - readline >=6.3
    - rpy2 >=2.8.2,<3
    - rubiks >=20070912
    - rw >=0.7
    - sagelib {{ version }}
    - sagemath-db-combinatorial-designs >=20140630
    - sagemath-db-conway-polynomials >=0.5.*
    - sagemath-db-elliptic-curves >=0.8
    - sagemath-db-graphs >=20161026
    - sagemath-db-polytopes >=20170220
    - scipy >=0.19.1
    - simplegeneric >=0.8.1
    - singledispatch >=3.4.0.3,<4
    - singular >=4.1.0p3,<5
    - six >=1.11.0,<2
    - sphinx >=1.6.3,<2
    - sqlite >=3.22,<4
    - ssl_match_hostname >=3.5.0.1,<4                   # [py27]
    - symmetrica >=2.0,<3
    - sympow >=1.018.1,<2
    - sympy >=1.1.1,<2
    - tachyon 0.99*
    - terminado >=0.8.1
    - tornado >=4.5.2,<5
    - traitlets >=4.3.2,<5
    - twisted >=18.4.0,<19
    - wcwidth >=0.1.7
    - widgetsnbextension >=3.1.1,<4
    - zeromq >=4.0.5,<5
    - zlib >=1.2.11,<2
    - zn_poly >=0.9

    #- sagetex
    #- pillow

    # sagenb dependencies with conda-packages
    #- itsdangerous
    #- flask
    #- flask-babel
    #- flask-openid
    #- markupsafe
    #- python-openid
    #- twisted
    #- speaklater
    #- werkzeug
    #- zope.interface

    # sagenb dependencies
    #- jmol
    #- mathjax
    #- tachyon
    #- thebe
    #- sagenb
    #- sagenb_export
    #- flask_autoindex
    #- flask_oldsessions
    #- flask_silk

    # docs
    #- sphinx
    #- snowballstemmer
    #- imagesize

    # dev
    #- bzip2
    #- gcc
    #- git

    # build-time dependencies
    #- vcversioner
    #- setuptools_scm

test:
  commands:
    - sage -v
    - sage -c 1+1

about:
  home: http://sagemath.org
  license: GPLv2+
  summary: 'Sage - Open Source Mathematical Software'
  description: |
    Creating a Viable Open Source Alternative to Magma, Maple, Mathematica, and MATLAB.
  doc_url: https://doc.sagemath.org/
  dev_url: https://trac.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
