schema_version: 1

context:
  version: "10.8"
  name: sagelib

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/sagemath/sage/archive/${{ version }}.tar.gz
  sha256: 496f90f77b569cb3c93610219d92d4abd390caf909e11f4f01d0d37d86017c8e

build:
  number: 0
  skip: win or match(python, "<3.12") or match(python, ">3.14")

requirements:
  build:
    - libtool
    - automake
    - m4
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('fortran') }}
    - make
    - pkg-config
    - gettext
    - meson
    - ninja
    - jinja2        3.1.*
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - cython        >=3.2
    - cysignals
    - memory-allocator
    - numpy
    - cypari2       >=2.2
    - gmpy2
    - numpy
  host:
    - pip
    - meson-python
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libboost-headers
    - cliquer       1.23.*
    - cypari2       2.2.*
    - cysignals     1.12.*
    - cython        3.1.*
    - ecl           >=24.5.10,<25
    - eclib
    - ecm           7.*
    - expat
    - fflas-ffpack  2.5.*
    - future
    - gap-core      4.14.0.*
    - giac          1.9.*
    - givaro        4.2.*
    - glpk
    - gmp
    - gmpy2         >=2.2.1,<3
    - gsl
    - iml           1.0.*
    - jinja2        3.1.*
    - jupyter_core  >=5.8.1,<6
    - lcalc         2.1.*
    - libbraiding   1.3.1.*
    - libbrial      1.2.*
    - libflint
    - libgd         2.3.*
    - libhomfly     1.03.*
    - libpng
    - linbox        >=1.7.1
    - lrcalc        2.1.*
    - m4ri
    - m4rie
    - maxima        5.47.0.*
    - memory-allocator
    - mpc           1.*
    - mpfi          1.5.*
    - mpfr
    - ntl           >=11.6.0,<12
    - numpy
    - pari
    - pkg-config
    - pkgconfig
    - planarity     4.*
    - ppl           1.2.*
    - pplpy         0.8.*
    - python
    - readline
    - rw            0.9.*
    - singular      ==4.4.1.p5
    - six
    - symmetrica    3.1.*
    - zlib
    # sage runtime deps
    - ipython       >=8.18.1,<9
    - pexpect       >=4.9.0,<5
    # for the symlinks
    - threejs-sage
    - notebook
    - jmol

    # sagelib needs bliss at build time but not at runtime, see sagemath-bliss
    - bliss >=0.77
    # sagelib needs sirocco at build time but not at runtime, see sagemath-sirocco
    - sirocco      >=2.1.1,<3

  # We can not include all actual runtime dependencies of Sage here as some of
  # them require Sage to build, such as some of the database packages.
  # The packages listed here are taken from the `SAGERUNTIME` variable in
  # `build/make/Makefile`.
  # These dependencies are enough to `import sage` and start `sage` but lots of
  # things do not work. To get all the standard dependencies of Sage, install
  # the "sage" package (which requires this "sagelib" package.)
  # By now we could probably drpo this separation and just use the new naming
  # from upstream, i.e., sagelib, sagemath-bliss, sagemath-sirocco
  # and create one output called sage which would probably be an alias for
  # sagelib. Until there is a sagemath-core or something like that,
  # we should probably keep sagelib around to be some minimal distribution.
  # See #169 for details.
  run:
    - ${{ pin_compatible("cypari2") }}
    - ${{ pin_compatible("cysignals") }}
    - ${{ pin_compatible("cython") }}
    - ${{ pin_compatible("ecl", upper_bound="x.x") }}
    - future
    - ${{ pin_compatible("gap-core", upper_bound="x.x") }}
    - ${{ pin_compatible("giac", upper_bound="x.x") }}
    - ${{ pin_compatible("gmpy2", upper_bound="x.x") }}
    - ${{ pin_compatible("jinja2", upper_bound="x.x") }}
    - ${{ pin_compatible("jupyter_core") }}
    - memory-allocator
    - ${{ pin_compatible("pplpy", upper_bound="x.x") }}
    - primecountpy >=0.1.1,<0.2.0
    - python
    - six
    - ${{ pin_compatible("pexpect") }}
    - python-lrcalc
    - ${{ pin_compatible("threejs-sage") }}
    # Disable ipython 8.19.0 which breaks the interactive session, see https://github.com/sagemath/sage/issues/36975
    - ipython >=8.18.1,<9,!=8.19.0
    # sage.features.all cannot be loaded without packaging (used by the fricas feature)
    - packaging
  ignore_run_exports:
    from_package:
      - ${{ compiler('fortran') }}
      - sirocco
      - bliss

tests:
  - python:
      imports:
        - sage
      pip_check: false
  - files:
      source:
        - src/sage/version.py
    requirements:
      run:
        - sympy
        - ipywidgets
        - pip
    script:
      env:
        # HOME (or DOT_SAGE) must be set for the CLI to be functional.
        HOME: .
      content: |
        sage --version
        # too many doctests fail still to run the entire test suite but we test that the doctesting framework works by testing a trivial file
        python -m sage.doctest src/sage/version.py
        sage -c 'print(1+1)'
        sage -c 'import sage.modular.multiple_zeta'

about:
  license: GPL-2.0-or-later
  license_file: COPYING.txt
  summary: Open Source Mathematical Software
  homepage: https://www.sagemath.org
  repository: https://github.com/sagemath/sage
  documentation: https://doc.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
    - alexjbest

