schema_version: 1

context:
  version: "10.8"
  name: sagelib

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/sagemath/sage/archive/${{ version }}.tar.gz
  sha256: 496f90f77b569cb3c93610219d92d4abd390caf909e11f4f01d0d37d86017c8e
  patches:
    # See https://github.com/sagemath/sage/issues/42002
    - 0001-Allow-SageMath-to-start-when-neither-HOME-nor-DOT_SA.patch

build:
  number: 0
  skip: win or match(python, "<3.12") or match(python, ">3.14")

outputs:
  - package:
      name: sagelib
    requirements:
      build:
        - libtool
        - automake
        - m4
        - ${{ compiler('cxx') }}
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('fortran') }}
        - make
        - pkg-config
        - gettext
        - ninja
        - jinja2        3.1.*
        - if: build_platform != target_platform
          then: python
        - if: build_platform != target_platform
          then: cross-python_${{ target_platform }}
        - if: build_platform != target_platform
          then: cython        3.1.*
        - cysignals
        - memory-allocator
        - numpy
        - cypari2       >=2.2
        - gmpy2
        - numpy
      host:
        - pip
        - meson-python
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - libboost-headers
        - cliquer       1.23.*
        - cypari2       2.2.*
        - cysignals     1.12.*
        - cython        3.1.*
        - ecl           >=24.5.10,<25
        - eclib
        - ecm           7.*
        - expat
        - fflas-ffpack  2.5.*
        - future
        - gap-core      4.14.0.*
        - giac          1.9.*
        - givaro        4.2.*
        - glpk
        - gmp
        - gmpy2         >=2.2.1,<3
        - gsl
        - iml           1.0.*
        - jinja2        3.1.*
        - jupyter_core  >=5.8.1,<6
        - lcalc         2.1.*
        - libbraiding   1.3.1.*
        - libbrial      1.2.*
        - libflint
        - libgd         2.3.*
        - libhomfly     1.03.*
        - libpng
        - linbox        >=1.7.1
        - lrcalc        2.1.*
        - m4ri
        - m4rie
        - maxima        5.47.0.*
        - memory-allocator
        - mpc           1.*
        - mpfi          1.5.*
        - mpfr
        - ntl
        - numpy
        - pari
        - pkg-config
        - pkgconfig
        - planarity     4.*
        - ppl           1.2.*
        - pplpy         0.8.*
        - python
        - readline
        - rw            0.9.*
        - singular      ==4.4.1.p5
        - six
        - symmetrica    3.1.*
        - zlib
        # sage runtime deps
        - ipython       >=8.18.1,<9
        - pexpect       >=4.9.0,<5
        # for the symlinks
        - threejs-sage
        - notebook
        - jmol

        # sagelib needs bliss at build time but not at runtime, see sagemath-bliss
        - bliss >=0.77
        # sagelib needs sirocco at build time but not at runtime, see sagemath-sirocco
        - sirocco      >=2.1.1,<3

      # We can not include all actual runtime dependencies of Sage here as some of
      # them require Sage to build, such as some of the database packages.
      # The packages listed here were taken from the `SAGERUNTIME` variable in
      # `build/make/Makefile`.
      # These dependencies are enough to `import sage` and start `sage` but lots of
      # things do not work. To get all the standard dependencies of Sage, install
      # the "sage" package (which requires this "sagelib" package.)
      # By now we could probably drop this separation and create one feedstock
      # with possibly multiple outputs.
      # However, a more minimal distribution of SageMath, such as this sagelib,
      # is often useful. Until there is some notion of a sagemath-core we
      # should probably keep sagelib around therefore.
      # See #169 for details.
      run:
        - ${{ pin_compatible("cypari2") }}
        - ${{ pin_compatible("cysignals") }}
        - ${{ pin_compatible("cython") }}
        - ${{ pin_compatible("ecl", upper_bound="x.x") }}
        - future
        - ${{ pin_compatible("gap-core", upper_bound="x.x") }}
        - ${{ pin_compatible("giac", upper_bound="x.x") }}
        - ${{ pin_compatible("gmpy2", upper_bound="x.x") }}
        - ${{ pin_compatible("jinja2", upper_bound="x.x") }}
        - ${{ pin_compatible("jupyter_core") }}
        - memory-allocator
        - ${{ pin_compatible("pplpy", upper_bound="x.x") }}
        - primecountpy >=0.1.1,<0.2.0
        - python
        - six
        - ${{ pin_compatible("pexpect") }}
        - python-lrcalc
        - ${{ pin_compatible("threejs-sage") }}
        # Disable ipython 8.19.0 which breaks the interactive session, see https://github.com/sagemath/sage/issues/36975
        - ipython >=8.18.1,<9,!=8.19.0
        # sage.features.all cannot be loaded without packaging (used by the fricas feature)
        - packaging
      ignore_run_exports:
        from_package:
          - ${{ compiler('fortran') }}
          # Ideally, we'd only build the glue code for sirocco but not install that glue glue code.
          # However, this is currently not really supported in the meson setup,
          # so we just install the glue code and depend on sirocco normally
          # (since sirocco has no problematic dependencies, this only increases
          # the size of sagelib a bit but should otherwise not be a problem.)
          # - sirocco
          # Same comments as for sirocco also apply to bliss.
          # - bliss
    tests:
      - python:
          imports:
            - sage.all
          pip_check: false
      - files:
          source:
            - src/sage/version.py
        requirements:
          run:
            - sympy
            - ipywidgets
            - pip
        script:
          content: |
            sage --version
            # too many doctests fail still to run the entire test suite but we test that the doctesting framework works by testing a trivial file
            python -m sage.doctest src/sage/version.py
            sage -c 'print(1+1)'
            sage -c 'import sage.modular.multiple_zeta'
  # Currently, there is no real sagemath-bliss or sagemath-sirocco package
  # supported by SageMath upstream anymore so we actually include them in the
  # sagelib package.
  # We could roll our own package separation by just including the relevant .so
  # files in sagemath-bliss and sagemath-sirocco. However, without support for
  # staging outputs this is very tedious, see
  # https://github.com/conda/ceps/pull/102 and
  # https://github.com/conda-forge/conda-smithy/issues/2057.
  # In the meantime, we keep these packages around so workflows that use them
  # can be easily upgraded and because we think that we'll likely bring such
  # packages back to support optional dependencies better.
  - package:
      name: sagemath-bliss
    build:
      script: install-sagemath-bliss.sh
    requirements:
      run:
        - ${{ pin_subpackage('sagelib', exact=True) }}
    tests:
      - python:
          imports:
            - sage.graphs.bliss
          pip_check: false
  - package:
      name: sagemath-sirocco
    build:
      script: install-sagemath-sirocco.sh
    requirements:
      run:
        - ${{ pin_subpackage('sagelib', exact=True) }}
    tests:
      - python:
          imports:
            - sage.libs.sirocco
          pip_check: false


about:
  license: GPL-2.0-or-later
  license_file: COPYING.txt
  summary: Open Source Mathematical Software
  homepage: https://www.sagemath.org
  repository: https://github.com/sagemath/sage
  documentation: https://doc.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
    - alexjbest
